-- Pratos proteicos pós-treino (5 novas receitas)
INSERT INTO recipes (category_id, title, description, image_url, prep_time, ingredients, instructions, tips, calories, protein, carbs, servings) VALUES
('19ed56f4-6e51-402f-8f30-acb711d6cb16', 'Frango Grelhado com Arroz Integral', 'Prato clássico pós-treino com carboidratos complexos', 'frango-arroz-integral.jpg', 30, ARRAY['200g de peito de frango', '1/2 xícara de arroz integral', 'Brócolis no vapor', 'Azeite', 'Limão e temperos'], ARRAY['Tempere o frango com limão e ervas', 'Grelhe em frigideira quente por 6-7 minutos de cada lado', 'Cozinhe o arroz integral conforme instruções', 'Prepare o brócolis no vapor por 5 minutos', 'Monte o prato e finalize com azeite'], 'Prepare o arroz com antecedência para refeições rápidas. O frango pode ser marinado na noite anterior.', 385, 42, 32, 1),

('19ed56f4-6e51-402f-8f30-acb711d6cb16', 'Omelete Proteico de 4 Ovos', 'Omelete reforçado para ganho muscular', 'omelete-proteico.jpg', 12, ARRAY['4 ovos inteiros', '2 claras extras', 'Espinafre', 'Queijo cottage', 'Tomate picado', 'Sal e pimenta'], ARRAY['Bata os ovos e claras com sal e pimenta', 'Aqueça frigideira antiaderente com pouco azeite', 'Despeje a mistura e espalhe uniformemente', 'Adicione recheios de um lado quando firmar', 'Dobre e sirva'], 'Não mexa demais para manter a textura macia. Adicione aveia na massa para mais fibras.', 345, 32, 6, 1),

('19ed56f4-6e51-402f-8f30-acb711d6cb16', 'Bowl de Frango com Feijão', 'Bowl nutritivo com proteínas completas', 'bowl-frango-feijao.jpg', 25, ARRAY['150g de frango desfiado', '1/2 xícara de feijão cozido', '1/2 xícara de arroz integral', 'Cenoura ralada', 'Coentro e limão'], ARRAY['Prepare o frango grelhado e desfie', 'Aqueça o feijão já cozido', 'Cozinhe o arroz integral', 'Monte o bowl com todos ingredientes', 'Finalize com cenoura, coentro e limão'], 'A combinação arroz + feijão forma proteína completa. Prepare em lotes para a semana toda.', 420, 38, 45, 1),

('19ed56f4-6e51-402f-8f30-acb711d6cb16', 'Shake Pós-Treino Caseiro', 'Shake proteico sem suplementos industriais', 'shake-caseiro.jpg', 5, ARRAY['200ml de leite desnatado', '1 banana', '2 colheres de aveia', '1 colher de pasta de amendoim', '1 ovo pasteurizado', 'Canela'], ARRAY['Coloque todos os ingredientes no liquidificador', 'Bata até ficar homogêneo', 'Adicione gelo se preferir gelado', 'Sirva imediatamente após o treino'], 'Use ovo pasteurizado para segurança. Adicione cacau para sabor chocolate.', 365, 22, 42, 1),

('19ed56f4-6e51-402f-8f30-acb711d6cb16', 'Carne Magra com Legumes', 'Prato proteico com vegetais nutritivos', 'carne-legumes.jpg', 30, ARRAY['200g de patinho em cubos', '1 abobrinha', '1 cenoura', '1 cebola', 'Alho e ervas', 'Azeite'], ARRAY['Corte a carne em cubos e tempere', 'Sele a carne em frigideira quente', 'Reserve e refogue os legumes em cubos', 'Junte a carne e finalize com ervas', 'Sirva com arroz integral se desejar'], 'Escolha cortes magros como patinho ou coxão mole. Deixe a carne descansar antes de servir.', 295, 36, 12, 1);

-- Refeições completas pra comer despreocupado (5 novas receitas)
INSERT INTO recipes (category_id, title, description, image_url, prep_time, ingredients, instructions, tips, calories, protein, carbs, servings) VALUES
('fcbcd4ad-98c8-452e-9b71-5b31ec0ffc9d', 'Marmita Fitness Completa', 'Marmita equilibrada com todos nutrientes', 'marmita-fitness.jpg', 35, ARRAY['150g de frango grelhado', '1/2 xícara de arroz integral', '1/2 xícara de feijão', 'Salada de folhas', 'Legumes cozidos'], ARRAY['Prepare o frango grelhado e corte', 'Cozinhe arroz e feijão separadamente', 'Prepare os legumes no vapor', 'Monte a marmita em porções equilibradas', 'Armazene na geladeira por até 3 dias'], 'Prepare 5 marmitas no domingo para a semana toda. Congele se necessário.', 445, 38, 48, 1),

('fcbcd4ad-98c8-452e-9b71-5b31ec0ffc9d', 'Prato Low Carb de Frango', 'Refeição completa com baixo carboidrato', 'prato-lowcarb.jpg', 25, ARRAY['200g de peito de frango', 'Couve-flor em arroz', 'Brócolis', 'Azeite de oliva', 'Limão e ervas'], ARRAY['Grelhe o frango temperado', 'Processe a couve-flor para fazer arroz', 'Refogue o arroz de couve-flor', 'Prepare brócolis no vapor', 'Monte o prato colorido'], 'Arroz de couve-flor tem 80% menos carboidratos. Tempere bem para realçar sabor.', 285, 38, 12, 1),

('fcbcd4ad-98c8-452e-9b71-5b31ec0ffc9d', 'Cardápio Detox do Dia', 'Combo completo para dia de desintoxicação', 'cardapio-detox.jpg', 40, ARRAY['Suco verde detox', 'Salada colorida', 'Sopa de legumes', 'Chá de hibisco', 'Frutas da estação'], ARRAY['Manhã: prepare o suco verde com couve e limão', 'Almoço: monte salada com folhas e legumes crus', 'Jantar: sopa leve de legumes', 'Lanches: frutas e chá de hibisco', 'Beba muita água durante o dia'], 'Faça 1x por semana para manter o corpo limpo. Evite proteínas animais neste dia.', 350, 12, 65, 1),

('fcbcd4ad-98c8-452e-9b71-5b31ec0ffc9d', 'Panqueca de Frango Completa', 'Panqueca recheada que é uma refeição completa', 'panqueca-frango-completa.jpg', 30, ARRAY['2 ovos', '3 colheres de aveia', 'Leite desnatado', '150g de frango desfiado', 'Molho de tomate caseiro', 'Queijo cottage'], ARRAY['Bata ovos, aveia e leite para massa', 'Faça panquecas finas na frigideira', 'Refogue o frango desfiado com temperos', 'Recheie as panquecas e enrole', 'Cubra com molho e leve ao forno'], 'Congele as panquecas prontas para refeições rápidas. Varie o recheio com carne ou legumes.', 385, 36, 28, 2),

('fcbcd4ad-98c8-452e-9b71-5b31ec0ffc9d', 'Lasanha de Berinjela Low Carb', 'Lasanha saudável usando berinjela como massa', 'lasanha-berinjela.jpg', 45, ARRAY['2 berinjelas grandes', '300g de carne moída magra', 'Molho de tomate caseiro', 'Queijo cottage', 'Queijo minas ralado', 'Orégano'], ARRAY['Corte berinjelas em fatias finas no sentido do comprimento', 'Grelhe as fatias levemente', 'Prepare a carne com molho de tomate', 'Monte camadas: berinjela, carne, cottage', 'Finalize com queijo e asse a 200°C por 20 min'], 'Salgar a berinjela antes ajuda a tirar água e amargor. Fica melhor no dia seguinte.', 325, 32, 18, 4);

-- Saladas criativas e saborosas (5 novas receitas)
INSERT INTO recipes (category_id, title, description, image_url, prep_time, ingredients, instructions, tips, calories, protein, carbs, servings) VALUES
('05b1977b-d73d-4b26-90e3-a87646787207', 'Salada de Atum Completa', 'Salada proteica com atum em lata', 'salada-atum-completa.jpg', 12, ARRAY['1 lata de atum light', 'Mix de folhas verdes', 'Tomate cereja', 'Pepino', 'Cebola roxa', 'Azeite e limão'], ARRAY['Escorra bem o atum', 'Lave e seque as folhas', 'Corte os vegetais em pedaços', 'Monte a salada em camadas', 'Tempere com azeite e limão na hora'], 'Use atum em água para menos calorias. Adicione ovo cozido para mais proteína.', 225, 28, 8, 1),

('05b1977b-d73d-4b26-90e3-a87646787207', 'Salada de Frango com Abacate', 'Salada cremosa com gorduras boas', 'salada-frango-abacate.jpg', 15, ARRAY['150g de frango grelhado', 'Mix de folhas', '1/2 abacate', 'Tomate', 'Cenoura ralada', 'Molho de iogurte'], ARRAY['Grelhe e corte o frango em tiras', 'Prepare as folhas lavadas e secas', 'Corte o abacate em fatias', 'Monte a salada colorida', 'Finalize com molho de iogurte'], 'O abacate oxida rápido, corte na hora de servir. Molho de iogurte é mais leve que maionese.', 345, 32, 14, 1),

('05b1977b-d73d-4b26-90e3-a87646787207', 'Salada de Ovo Cozido', 'Salada simples e nutritiva com ovos', 'salada-ovo-cozido.jpg', 15, ARRAY['3 ovos cozidos', 'Alface americana', 'Tomate', 'Pepino', 'Cenoura ralada', 'Mostarda e azeite'], ARRAY['Cozinhe os ovos por 10 minutos', 'Resfrie e descasque os ovos', 'Prepare os vegetais cortados', 'Corte os ovos em quartos', 'Tempere com mostarda diluída em azeite'], 'Ovos cozidos podem ser preparados com antecedência. Guarde descascados em água na geladeira.', 265, 18, 10, 1),

('05b1977b-d73d-4b26-90e3-a87646787207', 'Salada Verde Detox', 'Salada purificante com ingredientes verdes', 'salada-verde-detox.jpg', 10, ARRAY['Rúcula', 'Espinafre baby', 'Pepino', 'Salsão', 'Maçã verde', 'Hortelã e limão'], ARRAY['Lave bem todos os vegetais', 'Corte pepino e salsão em rodelas finas', 'Pique a maçã em cubos pequenos', 'Misture tudo com as folhas', 'Tempere com limão, azeite e hortelã'], 'Ideal para dias após exageros alimentares. A maçã verde dá um toque adocicado natural.', 85, 3, 16, 1),

('05b1977b-d73d-4b26-90e3-a87646787207', 'Salada Mediterrânea', 'Salada fresca inspirada na dieta mediterrânea', 'salada-mediterranea.jpg', 12, ARRAY['Tomate em cubos', 'Pepino', 'Cebola roxa', 'Azeitonas pretas', 'Queijo feta light', 'Orégano e azeite'], ARRAY['Corte tomate e pepino em cubos', 'Fatie a cebola roxa em meias luas', 'Adicione azeitonas cortadas', 'Esfarele o queijo feta por cima', 'Tempere com orégano e bom azeite'], 'Não adicione sal, o queijo feta já é salgado. Deixe descansar 10 min para pegar sabor.', 165, 8, 12, 1);

-- Sobremesas fit irresistíveis (5 novas receitas)
INSERT INTO recipes (category_id, title, description, image_url, prep_time, ingredients, instructions, tips, calories, protein, carbs, servings) VALUES
('3bd3f322-67b8-4258-979c-fe9a17cea503', 'Brownie Fit de Batata Doce', 'Brownie úmido com batata doce', 'brownie-batata.jpg', 35, ARRAY['1 batata doce média cozida', '3 colheres de cacau em pó', '2 ovos', '3 colheres de farinha de aveia', 'Adoçante', 'Gotas de chocolate 70%'], ARRAY['Amasse a batata doce cozida', 'Misture com ovos, cacau e farinha', 'Adicione adoçante e gotas de chocolate', 'Despeje em forma untada', 'Asse a 180°C por 25 minutos'], 'Não asse demais para manter úmido. Espere esfriar para cortar pois fica mais firme.', 145, 5, 22, 8),

('3bd3f322-67b8-4258-979c-fe9a17cea503', 'Sorvete de Morango Caseiro', 'Sorvete cremoso apenas com frutas', 'sorvete-morango.jpg', 10, ARRAY['2 xícaras de morangos congelados', '1 banana congelada', '2 colheres de iogurte natural', 'Adoçante a gosto'], ARRAY['Congele as frutas por pelo menos 6 horas', 'Bata tudo no processador até cremoso', 'Raspe as laterais e bata novamente', 'Sirva imediatamente', 'Decore com morango fresco'], 'Use frutas bem congeladas para textura de sorvete. Coma imediatamente ou recongelará duro.', 95, 3, 20, 2),

('3bd3f322-67b8-4258-979c-fe9a17cea503', 'Bolo de Cenoura Fit', 'Bolo clássico em versão saudável', 'bolo-cenoura-fit.jpg', 40, ARRAY['2 cenouras médias', '3 ovos', '1 xícara de farinha de aveia', '1/2 xícara de adoçante culinário', 'Óleo de coco', 'Fermento'], ARRAY['Bata no liquidificador cenouras, ovos e óleo', 'Adicione farinha, adoçante e fermento', 'Misture bem e despeje em forma', 'Asse a 180°C por 35 minutos', 'Faça cobertura de cacau com leite de coco'], 'Faça palito no centro, se sair limpo está pronto. A cobertura é opcional.', 125, 4, 18, 10),

('3bd3f322-67b8-4258-979c-fe9a17cea503', 'Docinho de Leite em Pó', 'Docinho fácil e proteico', 'docinho-leite.jpg', 15, ARRAY['1 xícara de leite em pó desnatado', '3 colheres de leite desnatado', 'Adoçante a gosto', 'Cacau em pó para enrolar', 'Coco ralado para enrolar'], ARRAY['Misture leite em pó com leite líquido', 'Adicione adoçante e amasse até dar ponto', 'Faça bolinhas pequenas', 'Passe no cacau ou coco', 'Leve à geladeira por 1 hora'], 'Se a massa estiver seca, adicione mais leite. Rende cerca de 20 docinhos.', 35, 2, 4, 20),

('3bd3f322-67b8-4258-979c-fe9a17cea503', 'Paçoca Fit', 'Paçoca caseira sem açúcar', 'pacoca-fit.jpg', 10, ARRAY['1 xícara de amendoim torrado', '3 colheres de leite em pó', 'Adoçante a gosto', '1 colher de óleo de coco', 'Pitada de sal'], ARRAY['Processe o amendoim até virar pasta', 'Adicione leite em pó e adoçante', 'Acrescente óleo de coco e sal', 'Misture bem e molde em forminhas', 'Leve à geladeira para firmar'], 'Use amendoim sem sal e sem pele. Conserve na geladeira por até 2 semanas.', 85, 4, 5, 12);