-- Corrigir URLs das imagens no banco de dados
UPDATE recipes SET image_url = 'ovo-abacate.jpg' WHERE title = 'Ovo Cozido com Abacate';
UPDATE recipes SET image_url = 'panqueca-abobrinha.jpg' WHERE title = 'Panqueca de Abobrinha';
UPDATE recipes SET image_url = 'suco-verde-detox.jpg' WHERE title = 'Suco Verde Detox';
UPDATE recipes SET image_url = 'vitamina-banana.jpg' WHERE title = 'Vitamina de Banana com Aveia';
UPDATE recipes SET image_url = 'wrap-ovo.jpg' WHERE title = 'Wrap Integral de Ovo';
UPDATE recipes SET image_url = 'banana-caramelizada.jpg' WHERE title = 'Banana Caramelizada Fit';
UPDATE recipes SET image_url = 'bombom-coco.jpg' WHERE title = 'Bombom de Coco Fit';
UPDATE recipes SET image_url = 'cocada-fit.jpg' WHERE title = 'Cocada Fit de Forno';
UPDATE recipes SET image_url = 'frozen-iogurte.jpg' WHERE title = 'Frozen de Iogurte com Frutas';
UPDATE recipes SET image_url = 'gelatina-proteica.jpg' WHERE title = 'Gelatina Proteica de Frutas';
UPDATE recipes SET image_url = 'berinjela-recheada.jpg' WHERE title = 'Berinjela Recheada Light';
UPDATE recipes SET image_url = 'canja-leve.jpg' WHERE title = 'Canja Leve de Frango';
UPDATE recipes SET image_url = 'omelete-forno-jantar.jpg' WHERE title = 'Omelete de Forno com Legumes';
UPDATE recipes SET image_url = 'salada-jantar.jpg' WHERE title = 'Salada de Jantar Completa';
UPDATE recipes SET image_url = 'sopa-detox.jpg' WHERE title = 'Sopa Detox de Legumes';
UPDATE recipes SET image_url = 'chips-abobrinha.jpg' WHERE title = 'Chips de Abobrinha';
UPDATE recipes SET image_url = 'crepioca-queijo.jpg' WHERE title = 'Crepioca de Queijo e Tomate';
UPDATE recipes SET image_url = 'mix-oleaginosas.jpg' WHERE title = 'Mix de Oleaginosas';
UPDATE recipes SET image_url = 'pate-atum.jpg' WHERE title = 'Patê de Atum Light';
UPDATE recipes SET image_url = 'rolinho-peru.jpg' WHERE title = 'Rolinho de Peito de Peru';
UPDATE recipes SET image_url = 'bowl-frango-feijao.jpg' WHERE title = 'Bowl de Frango com Feijão';
UPDATE recipes SET image_url = 'carne-legumes.jpg' WHERE title = 'Carne Magra com Legumes';
UPDATE recipes SET image_url = 'frango-arroz-integral.jpg' WHERE title = 'Frango Grelhado com Arroz Integral';
UPDATE recipes SET image_url = 'omelete-proteico.jpg' WHERE title = 'Omelete Proteico de 4 Ovos';
UPDATE recipes SET image_url = 'shake-caseiro.jpg' WHERE title = 'Shake Pós-Treino Caseiro';
UPDATE recipes SET image_url = 'cardapio-detox.jpg' WHERE title = 'Cardápio Detox do Dia';
UPDATE recipes SET image_url = 'lasanha-berinjela.jpg' WHERE title = 'Lasanha de Berinjela Low Carb';
UPDATE recipes SET image_url = 'marmita-fitness.jpg' WHERE title = 'Marmita Fitness Completa';
UPDATE recipes SET image_url = 'panqueca-frango-completa.jpg' WHERE title = 'Panqueca de Frango Completa';
UPDATE recipes SET image_url = 'prato-lowcarb.jpg' WHERE title = 'Prato Low Carb de Frango';
UPDATE recipes SET image_url = 'salada-atum-completa.jpg' WHERE title = 'Salada de Atum Completa';
UPDATE recipes SET image_url = 'salada-frango-abacate.jpg' WHERE title = 'Salada de Frango com Abacate';
UPDATE recipes SET image_url = 'salada-ovo-cozido.jpg' WHERE title = 'Salada de Ovo Cozido';
UPDATE recipes SET image_url = 'salada-mediterranea.jpg' WHERE title = 'Salada Mediterrânea';
UPDATE recipes SET image_url = 'salada-verde-detox.jpg' WHERE title = 'Salada Verde Detox';
UPDATE recipes SET image_url = 'bolo-cenoura-fit.jpg' WHERE title = 'Bolo de Cenoura Fit';
UPDATE recipes SET image_url = 'brownie-batata.jpg' WHERE title = 'Brownie Fit de Batata Doce';
UPDATE recipes SET image_url = 'docinho-leite.jpg' WHERE title = 'Docinho de Leite em Pó';
UPDATE recipes SET image_url = 'pacoca-fit.jpg' WHERE title = 'Paçoca Fit';
UPDATE recipes SET image_url = 'sorvete-morango.jpg' WHERE title = 'Sorvete de Morango Caseiro';

-- Corrigir receitas que tinham URLs sem o caminho correto (sem /src/assets/recipes/)
UPDATE recipes SET image_url = 'crepioca-frango.jpg' WHERE title = 'Crepioca de Frango';
UPDATE recipes SET image_url = 'mingau-aveia.jpg' WHERE title = 'Mingau de Aveia Proteico';
UPDATE recipes SET image_url = 'omelete-legumes.jpg' WHERE title = 'Omelete de Legumes';
UPDATE recipes SET image_url = 'smoothie-verde.jpg' WHERE title = 'Smoothie Verde Energético';
UPDATE recipes SET image_url = 'torrada-abacate.jpg' WHERE title = 'Torrada Integral com Abacate';
UPDATE recipes SET image_url = 'beijinho-fit.jpg' WHERE title = 'Beijinho Fit';
UPDATE recipes SET image_url = 'bolo-caneca.jpg' WHERE title = 'Bolo de Caneca Fit';
UPDATE recipes SET image_url = 'pudim-proteina.jpg' WHERE title = 'Pudim de Proteína';
UPDATE recipes SET image_url = 'sorvete-banana.jpg' WHERE title = 'Sorvete de Banana';
UPDATE recipes SET image_url = 'trufa-tamaras.jpg' WHERE title = 'Trufa de Tâmaras';
UPDATE recipes SET image_url = 'abobrinha-recheada.jpg' WHERE title = 'Abobrinha Recheada';
UPDATE recipes SET image_url = 'creme-abobora.jpg' WHERE title = 'Creme de Abóbora';
UPDATE recipes SET image_url = 'omelete-forno.jpg' WHERE title = 'Omelete de Forno';
UPDATE recipes SET image_url = 'salada-morna.jpg' WHERE title = 'Salada Morna de Frango';
UPDATE recipes SET image_url = 'wrap-atum.jpg' WHERE title = 'Wrap de Atum';
UPDATE recipes SET image_url = 'bolinho-batata.jpg' WHERE title = 'Bolinho de Batata Doce';
UPDATE recipes SET image_url = 'muffin-espinafre.jpg' WHERE title = 'Muffin Salgado de Espinafre';
UPDATE recipes SET image_url = 'palitos-homus.jpg' WHERE title = 'Palitos de Cenoura com Homus';
UPDATE recipes SET image_url = 'sanduiche-frango.jpg' WHERE title = 'Sanduíche Natural de Frango';
UPDATE recipes SET image_url = 'smoothie-bowl.jpg' WHERE title = 'Smoothie Bowl de Açaí';
UPDATE recipes SET image_url = 'frango-quinoa.jpg' WHERE title = 'Peito de Frango Grelhado com Quinoa';
UPDATE recipes SET image_url = 'hamburguer-frango.jpg' WHERE title = 'Hambúrguer de Frango Caseiro';
UPDATE recipes SET image_url = 'omelete-claras.jpg' WHERE title = 'Omelete de Claras com Aveia';
UPDATE recipes SET image_url = 'panqueca-banana.jpg' WHERE title = 'Panqueca Proteica de Banana';
UPDATE recipes SET image_url = 'shake-morango.jpg' WHERE title = 'Shake Proteico de Morango';
UPDATE recipes SET image_url = 'escondidinho-frango.jpg' WHERE title = 'Escondidinho de Frango';
UPDATE recipes SET image_url = 'estrogonofe-light.jpg' WHERE title = 'Estrogonofe de Frango Light';
UPDATE recipes SET image_url = 'lasanha-abobrinha.jpg' WHERE title = 'Lasanha de Abobrinha';
UPDATE recipes SET image_url = 'marmita-carne.jpg' WHERE title = 'Marmita Fit de Carne';
UPDATE recipes SET image_url = 'poke-salmao.jpg' WHERE title = 'Poke Bowl de Salmão';
UPDATE recipes SET image_url = 'salada-beterraba.jpg' WHERE title = 'Salada de Beterraba com Queijo';
UPDATE recipes SET image_url = 'salada-grao-bico.jpg' WHERE title = 'Salada de Grão-de-Bico';
UPDATE recipes SET image_url = 'salada-lentilha.jpg' WHERE title = 'Salada de Lentilha';
UPDATE recipes SET image_url = 'salada-oriental.jpg' WHERE title = 'Salada Oriental de Repolho';
UPDATE recipes SET image_url = 'salada-tropical.jpg' WHERE title = 'Salada Tropical';
UPDATE recipes SET image_url = 'docinho-coco.jpg' WHERE title = 'Docinho de Coco';
UPDATE recipes SET image_url = 'mousse-maracuja.jpg' WHERE title = 'Mousse de Maracujá';
UPDATE recipes SET image_url = 'pave-chocolate.jpg' WHERE title = 'Pavê de Chocolate Fit';
UPDATE recipes SET image_url = 'picole-frutas.jpg' WHERE title = 'Picolé de Frutas';
UPDATE recipes SET image_url = 'torta-limao.jpg' WHERE title = 'Torta de Limão Fit';