-- Café da Manhã (11bff80f-bd8f-4c71-8c91-05256c8f4eaf)
INSERT INTO recipes (category_id, title, description, image_url, prep_time, calories, protein, carbs, servings, ingredients, instructions, tips) VALUES
('11bff80f-bd8f-4c71-8c91-05256c8f4eaf', 'Crepioca de Frango', 'Crepioca recheada com frango desfiado e requeijão light', 'crepioca-frango.jpg', 15, 320, 28, 22, 1, ARRAY['2 ovos', '2 colheres de tapioca', '100g de frango desfiado', '1 colher de requeijão light', 'Temperos a gosto'], ARRAY['Misture os ovos com a tapioca até formar uma massa homogênea', 'Despeje em uma frigideira antiaderente aquecida', 'Deixe dourar de um lado e vire', 'Adicione o frango e o requeijão', 'Dobre e sirva quente'], 'Tempere o frango com ervas finas para mais sabor'),
('11bff80f-bd8f-4c71-8c91-05256c8f4eaf', 'Smoothie Verde Energético', 'Smoothie nutritivo com espinafre, banana e aveia', 'smoothie-verde.jpg', 5, 220, 8, 35, 1, ARRAY['1 banana congelada', '1 xícara de espinafre', '200ml de leite de amêndoas', '2 colheres de aveia', '1 colher de mel'], ARRAY['Adicione todos os ingredientes no liquidificador', 'Bata até ficar cremoso', 'Ajuste a consistência com mais leite se necessário', 'Sirva gelado'], 'Congele a banana na noite anterior para um smoothie mais cremoso'),
('11bff80f-bd8f-4c71-8c91-05256c8f4eaf', 'Omelete de Legumes', 'Omelete recheado com legumes frescos e queijo cottage', 'omelete-legumes.jpg', 12, 280, 22, 8, 1, ARRAY['3 ovos', '1/4 xícara de queijo cottage', '1/2 tomate picado', '1/4 cebola picada', 'Espinafre a gosto', 'Sal e pimenta'], ARRAY['Bata os ovos com sal e pimenta', 'Em uma frigideira, refogue rapidamente os legumes', 'Despeje os ovos batidos sobre os legumes', 'Adicione o cottage no centro', 'Dobre ao meio quando firmar'], 'Use frigideira antiaderente para não grudar'),
('11bff80f-bd8f-4c71-8c91-05256c8f4eaf', 'Mingau de Aveia Proteico', 'Mingau cremoso com whey protein e frutas', 'mingau-aveia.jpg', 10, 350, 30, 40, 1, ARRAY['1/2 xícara de aveia', '200ml de leite desnatado', '1 scoop de whey protein', '1/2 banana fatiada', 'Canela a gosto'], ARRAY['Cozinhe a aveia com o leite em fogo médio', 'Mexa constantemente até engrossar', 'Retire do fogo e deixe amornar', 'Misture o whey protein', 'Cubra com banana e canela'], 'Adicione o whey apenas depois de amornar para não perder nutrientes'),
('11bff80f-bd8f-4c71-8c91-05256c8f4eaf', 'Torrada Integral com Abacate', 'Torrada crocante com pasta de abacate temperada', 'torrada-abacate.jpg', 8, 290, 10, 28, 1, ARRAY['2 fatias de pão integral', '1/2 abacate maduro', 'Suco de 1/2 limão', 'Sal e pimenta', 'Tomate cereja para decorar'], ARRAY['Torre as fatias de pão', 'Amasse o abacate com um garfo', 'Tempere com limão, sal e pimenta', 'Espalhe sobre as torradas', 'Decore com tomates cereja cortados'], 'O limão evita que o abacate escureça');

-- Doces sem fugir da dieta (7431747a-5166-4cf9-a9d5-76d1d1cdf5ed)
INSERT INTO recipes (category_id, title, description, image_url, prep_time, calories, protein, carbs, servings, ingredients, instructions, tips) VALUES
('7431747a-5166-4cf9-a9d5-76d1d1cdf5ed', 'Bolo de Caneca Fit', 'Bolo individual de chocolate feito no micro-ondas', 'bolo-caneca.jpg', 5, 180, 12, 20, 1, ARRAY['1 ovo', '2 colheres de cacau em pó', '2 colheres de farinha de aveia', '1 colher de adoçante', '3 colheres de leite'], ARRAY['Misture todos os ingredientes em uma caneca', 'Mexa bem até ficar homogêneo', 'Leve ao micro-ondas por 2 minutos', 'Espere amornar antes de comer'], 'Não passe do tempo para não ressecar'),
('7431747a-5166-4cf9-a9d5-76d1d1cdf5ed', 'Sorvete de Banana', 'Sorvete cremoso feito apenas com banana congelada', 'sorvete-banana.jpg', 5, 120, 2, 28, 2, ARRAY['2 bananas congeladas', '1 colher de cacau em pó', '1 colher de pasta de amendoim'], ARRAY['Corte as bananas em rodelas e congele por 4 horas', 'Bata no processador até ficar cremoso', 'Adicione o cacau e a pasta de amendoim', 'Bata novamente e sirva imediatamente'], 'Bananas bem maduras ficam mais doces'),
('7431747a-5166-4cf9-a9d5-76d1d1cdf5ed', 'Trufa de Tâmaras', 'Trufa saudável de tâmaras com cacau e coco', 'trufa-tamaras.jpg', 15, 90, 2, 15, 8, ARRAY['10 tâmaras sem caroço', '2 colheres de cacau em pó', '1 colher de óleo de coco', 'Coco ralado para cobrir'], ARRAY['Processe as tâmaras até formar uma pasta', 'Adicione o cacau e o óleo de coco', 'Processe novamente', 'Faça bolinhas e passe no coco ralado', 'Leve à geladeira por 30 minutos'], 'Umedeça as mãos para não grudar ao modelar'),
('7431747a-5166-4cf9-a9d5-76d1d1cdf5ed', 'Pudim de Proteína', 'Pudim cremoso com whey protein sabor baunilha', 'pudim-proteina.jpg', 10, 150, 25, 8, 2, ARRAY['1 scoop de whey baunilha', '200ml de leite desnatado', '1 envelope de gelatina sem sabor', 'Adoçante a gosto'], ARRAY['Hidrate a gelatina em 2 colheres de água fria', 'Aqueça o leite sem ferver', 'Dissolva a gelatina no leite quente', 'Misture o whey e o adoçante', 'Leve à geladeira por 4 horas'], 'Sirva com frutas vermelhas por cima'),
('7431747a-5166-4cf9-a9d5-76d1d1cdf5ed', 'Beijinho Fit', 'Beijinho tradicional em versão saudável', 'beijinho-fit.jpg', 20, 80, 4, 10, 10, ARRAY['1 lata de leite condensado zero', '100g de coco ralado', '1 colher de manteiga light'], ARRAY['Misture todos os ingredientes em uma panela', 'Cozinhe em fogo baixo mexendo sempre', 'Quando desgrudar do fundo, desligue', 'Espere esfriar e faça bolinhas', 'Passe no coco ralado'], 'Use luvas de silicone para modelar mais fácil');

-- Jantares leves e nutritivos (18d7a8d4-e335-4731-9f8e-db4d32140013)
INSERT INTO recipes (category_id, title, description, image_url, prep_time, calories, protein, carbs, servings, ingredients, instructions, tips) VALUES
('18d7a8d4-e335-4731-9f8e-db4d32140013', 'Omelete de Forno', 'Omelete assado com legumes e queijo', 'omelete-forno.jpg', 25, 280, 22, 10, 2, ARRAY['4 ovos', '1/2 xícara de brócolis', '1/4 xícara de queijo cottage', '1/4 cebola picada', 'Sal e orégano'], ARRAY['Bata os ovos com sal', 'Misture os legumes picados', 'Despeje em forma untada', 'Cubra com cottage e orégano', 'Asse a 180°C por 20 minutos'], 'Sirva com salada verde'),
('18d7a8d4-e335-4731-9f8e-db4d32140013', 'Creme de Abóbora', 'Sopa cremosa de abóbora com gengibre', 'creme-abobora.jpg', 30, 180, 6, 25, 3, ARRAY['500g de abóbora', '1 cebola', '1 pedaço de gengibre', '500ml de caldo de legumes', 'Sal e noz-moscada'], ARRAY['Refogue a cebola com o gengibre', 'Adicione a abóbora em cubos', 'Cubra com o caldo e cozinhe até amaciar', 'Bata no liquidificador', 'Tempere e sirva'], 'Decore com sementes de abóbora torradas'),
('18d7a8d4-e335-4731-9f8e-db4d32140013', 'Wrap de Atum', 'Wrap integral recheado com atum e vegetais', 'wrap-atum.jpg', 10, 320, 28, 30, 1, ARRAY['1 wrap integral', '1 lata de atum light', '2 colheres de iogurte natural', 'Alface e tomate', 'Suco de limão'], ARRAY['Escorra bem o atum', 'Misture com iogurte e limão', 'Coloque a alface no wrap', 'Adicione o atum e o tomate', 'Enrole e sirva'], 'Use atum em água para menos gordura'),
('18d7a8d4-e335-4731-9f8e-db4d32140013', 'Abobrinha Recheada', 'Abobrinha recheada com carne moída magra', 'abobrinha-recheada.jpg', 35, 250, 24, 12, 2, ARRAY['2 abobrinhas médias', '200g de carne moída magra', '1/2 cebola', '1 tomate', 'Queijo cottage'], ARRAY['Corte as abobrinhas ao meio e retire o miolo', 'Refogue a carne com cebola e tomate', 'Recheie as abobrinhas', 'Cubra com cottage', 'Asse a 200°C por 25 minutos'], 'O miolo da abobrinha pode ir no recheio'),
('18d7a8d4-e335-4731-9f8e-db4d32140013', 'Salada Morna de Frango', 'Salada com frango grelhado e legumes assados', 'salada-morna.jpg', 25, 300, 32, 15, 1, ARRAY['150g de peito de frango', 'Mix de folhas verdes', '1/2 abobrinha', '1/2 pimentão', 'Azeite e limão'], ARRAY['Grelhe o frango temperado', 'Asse os legumes com azeite', 'Monte a salada com as folhas', 'Adicione os legumes e o frango fatiado', 'Tempere com azeite e limão'], 'Sirva enquanto os legumes ainda estão mornos');

-- Lanches rápidos e saudáveis (d639ae08-35ce-409d-a0f4-27e6db85dc2b)
INSERT INTO recipes (category_id, title, description, image_url, prep_time, calories, protein, carbs, servings, ingredients, instructions, tips) VALUES
('d639ae08-35ce-409d-a0f4-27e6db85dc2b', 'Sanduíche Natural de Frango', 'Sanduíche leve com frango desfiado e cottage', 'sanduiche-frango.jpg', 15, 280, 26, 25, 1, ARRAY['2 fatias de pão integral', '100g de frango desfiado', '2 colheres de cottage', 'Alface e tomate', 'Cenoura ralada'], ARRAY['Misture o frango com o cottage', 'Tempere a gosto', 'Monte o sanduíche com as folhas', 'Adicione a cenoura ralada', 'Feche e sirva'], 'Tempere o frango com curry para variar'),
('d639ae08-35ce-409d-a0f4-27e6db85dc2b', 'Palitos de Cenoura com Homus', 'Snack crocante com homus caseiro', 'palitos-homus.jpg', 10, 180, 8, 22, 2, ARRAY['2 cenouras médias', '1 xícara de grão-de-bico cozido', '2 colheres de tahine', 'Suco de 1 limão', 'Alho e sal'], ARRAY['Corte as cenouras em palitos', 'Bata o grão-de-bico com tahine e limão', 'Adicione alho e sal a gosto', 'Sirva os palitos com o homus'], 'Guarde o homus na geladeira por até 5 dias'),
('d639ae08-35ce-409d-a0f4-27e6db85dc2b', 'Bolinho de Batata Doce', 'Bolinho assado de batata doce e aveia', 'bolinho-batata.jpg', 25, 120, 5, 18, 6, ARRAY['1 batata doce média cozida', '3 colheres de aveia', '1 ovo', 'Sal e salsa picada', 'Queijo cottage'], ARRAY['Amasse a batata doce', 'Misture com aveia, ovo e temperos', 'Forme bolinhos e coloque em assadeira', 'Asse a 200°C por 20 minutos', 'Sirva com cottage'], 'Vire na metade do tempo para dourar dos dois lados'),
('d639ae08-35ce-409d-a0f4-27e6db85dc2b', 'Muffin Salgado de Espinafre', 'Mini muffin verde rico em nutrientes', 'muffin-espinafre.jpg', 25, 90, 6, 8, 6, ARRAY['2 xícaras de espinafre', '2 ovos', '3 colheres de farinha de aveia', '2 colheres de queijo ralado', 'Sal e noz-moscada'], ARRAY['Pique o espinafre finamente', 'Misture com ovos batidos', 'Adicione farinha e queijo', 'Despeje em forminhas', 'Asse a 180°C por 18 minutos'], 'Perfeito para levar no trabalho'),
('d639ae08-35ce-409d-a0f4-27e6db85dc2b', 'Smoothie Bowl de Açaí', 'Bowl de açaí com granola e frutas', 'smoothie-bowl.jpg', 8, 320, 8, 45, 1, ARRAY['100g de polpa de açaí', '1 banana congelada', '100ml de leite vegetal', 'Granola sem açúcar', 'Frutas frescas'], ARRAY['Bata o açaí com banana e leite', 'Despeje em uma tigela', 'Decore com granola e frutas', 'Sirva imediatamente'], 'Use frutas congeladas para consistência mais cremosa');

-- Pratos proteicos pós-treino (19ed56f4-6e51-402f-8f30-acb711d6cb16)
INSERT INTO recipes (category_id, title, description, image_url, prep_time, calories, protein, carbs, servings, ingredients, instructions, tips) VALUES
('19ed56f4-6e51-402f-8f30-acb711d6cb16', 'Shake Proteico de Morango', 'Shake cremoso pós-treino com frutas', 'shake-morango.jpg', 5, 280, 35, 25, 1, ARRAY['1 scoop de whey de morango', '200ml de leite desnatado', '5 morangos', '1 colher de aveia', 'Gelo a gosto'], ARRAY['Adicione todos os ingredientes no liquidificador', 'Bata até ficar cremoso', 'Ajuste a consistência com mais leite', 'Sirva gelado'], 'Adicione banana para mais cremosidade'),
('19ed56f4-6e51-402f-8f30-acb711d6cb16', 'Peito de Frango Grelhado com Quinoa', 'Frango suculento com quinoa e legumes', 'frango-quinoa.jpg', 30, 420, 45, 35, 1, ARRAY['200g de peito de frango', '1/2 xícara de quinoa', 'Brócolis e cenoura', 'Azeite e limão', 'Temperos a gosto'], ARRAY['Tempere e grelhe o frango', 'Cozinhe a quinoa conforme embalagem', 'Cozinhe os legumes no vapor', 'Monte o prato', 'Finalize com azeite e limão'], 'Deixe o frango descansar antes de fatiar'),
('19ed56f4-6e51-402f-8f30-acb711d6cb16', 'Omelete de Claras com Aveia', 'Omelete proteico com claras e fibras', 'omelete-claras.jpg', 10, 220, 28, 15, 1, ARRAY['5 claras de ovo', '2 colheres de aveia', '1/4 xícara de espinafre', 'Sal e pimenta', 'Queijo cottage'], ARRAY['Bata as claras com a aveia', 'Despeje em frigideira aquecida', 'Adicione o espinafre', 'Quando firmar, dobre ao meio', 'Sirva com cottage'], 'Use as gemas para outras receitas'),
('19ed56f4-6e51-402f-8f30-acb711d6cb16', 'Hambúrguer de Frango Caseiro', 'Hambúrguer proteico de peito de frango', 'hamburguer-frango.jpg', 20, 350, 38, 20, 2, ARRAY['300g de peito de frango moído', '1 ovo', '2 colheres de aveia', 'Cebola e alho', 'Temperos a gosto'], ARRAY['Misture todos os ingredientes', 'Forme hambúrgueres', 'Grelhe em frigideira ou churrasqueira', 'Sirva com salada ou em pão integral'], 'Faça em quantidade e congele'),
('19ed56f4-6e51-402f-8f30-acb711d6cb16', 'Panqueca Proteica de Banana', 'Panqueca fofa com alto teor proteico', 'panqueca-banana.jpg', 15, 320, 30, 30, 2, ARRAY['2 ovos', '1 banana', '1 scoop de whey baunilha', '2 colheres de aveia', 'Canela a gosto'], ARRAY['Bata todos os ingredientes no liquidificador', 'Aqueça frigideira antiaderente', 'Despeje porções da massa', 'Vire quando formar bolhas', 'Sirva com frutas'], 'Use banana bem madura para mais doçura natural');

-- Refeições completas (fcbcd4ad-98c8-452e-9b71-5b31ec0ffc9d)
INSERT INTO recipes (category_id, title, description, image_url, prep_time, calories, protein, carbs, servings, ingredients, instructions, tips) VALUES
('fcbcd4ad-98c8-452e-9b71-5b31ec0ffc9d', 'Marmita Fit de Carne', 'Marmita equilibrada com carne e legumes', 'marmita-carne.jpg', 35, 450, 35, 40, 1, ARRAY['150g de patinho moído', 'Arroz integral', 'Feijão', 'Brócolis e cenoura', 'Temperos naturais'], ARRAY['Cozinhe o arroz integral', 'Refogue a carne com temperos', 'Cozinhe o feijão', 'Prepare os legumes no vapor', 'Monte a marmita'], 'Prepare em quantidade para a semana'),
('fcbcd4ad-98c8-452e-9b71-5b31ec0ffc9d', 'Estrogonofe de Frango Light', 'Estrogonofe cremoso sem creme de leite', 'estrogonofe-light.jpg', 30, 380, 38, 28, 2, ARRAY['400g de peito de frango', '1 cebola', '200g de iogurte natural', '1 colher de mostarda', 'Champignon'], ARRAY['Corte o frango em cubos', 'Refogue com cebola', 'Adicione mostarda e champignon', 'Misture o iogurte no final', 'Sirva com arroz integral'], 'Não deixe ferver após adicionar o iogurte'),
('fcbcd4ad-98c8-452e-9b71-5b31ec0ffc9d', 'Escondidinho de Frango', 'Escondidinho com purê de batata doce', 'escondidinho-frango.jpg', 40, 380, 32, 35, 2, ARRAY['300g de frango desfiado', '2 batatas doces', '1 cebola', 'Queijo cottage', 'Temperos verdes'], ARRAY['Cozinhe e amasse as batatas doces', 'Refogue o frango com cebola', 'Monte camadas em refratário', 'Cubra com cottage', 'Gratine por 15 minutos'], 'Use queijo minas para gratinar melhor'),
('fcbcd4ad-98c8-452e-9b71-5b31ec0ffc9d', 'Poke Bowl de Salmão', 'Bowl havaiano com salmão fresco', 'poke-salmao.jpg', 20, 420, 30, 45, 1, ARRAY['150g de salmão fresco', 'Arroz de sushi', 'Pepino e abacate', 'Molho shoyu', 'Gergelim'], ARRAY['Cozinhe o arroz', 'Corte o salmão em cubos', 'Prepare os vegetais', 'Monte o bowl', 'Finalize com shoyu e gergelim'], 'Use salmão de qualidade para consumir cru'),
('fcbcd4ad-98c8-452e-9b71-5b31ec0ffc9d', 'Lasanha de Abobrinha', 'Lasanha low carb com abobrinha', 'lasanha-abobrinha.jpg', 45, 350, 30, 18, 2, ARRAY['2 abobrinhas', '300g de carne moída', 'Molho de tomate caseiro', 'Queijo cottage', 'Queijo minas'], ARRAY['Fatie as abobrinhas em lâminas', 'Refogue a carne com molho', 'Monte camadas alternando', 'Cubra com cottage e minas', 'Asse a 200°C por 30 minutos'], 'Seque as abobrinhas para não ficar aguado');

-- Saladas criativas (05b1977b-d73d-4b26-90e3-a87646787207)
INSERT INTO recipes (category_id, title, description, image_url, prep_time, calories, protein, carbs, servings, ingredients, instructions, tips) VALUES
('05b1977b-d73d-4b26-90e3-a87646787207', 'Salada Tropical', 'Salada refrescante com frutas e frango', 'salada-tropical.jpg', 15, 280, 25, 20, 1, ARRAY['Mix de folhas', '100g de frango grelhado', 'Manga em cubos', 'Abacaxi', 'Molho de iogurte'], ARRAY['Grelhe e fatie o frango', 'Corte as frutas', 'Monte a salada com as folhas', 'Adicione frango e frutas', 'Regue com molho de iogurte'], 'Use frutas bem geladas'),
('05b1977b-d73d-4b26-90e3-a87646787207', 'Salada de Grão-de-Bico', 'Salada mediterrânea nutritiva', 'salada-grao-bico.jpg', 15, 320, 15, 40, 2, ARRAY['1 xícara de grão-de-bico', 'Pepino e tomate', 'Cebola roxa', 'Salsinha', 'Azeite e limão'], ARRAY['Cozinhe o grão-de-bico', 'Pique os vegetais', 'Misture tudo em uma tigela', 'Tempere com azeite e limão', 'Finalize com salsinha'], 'Deixe marinar por 30 minutos'),
('05b1977b-d73d-4b26-90e3-a87646787207', 'Salada de Beterraba com Queijo', 'Salada colorida com beterraba assada', 'salada-beterraba.jpg', 40, 250, 12, 25, 2, ARRAY['2 beterrabas', 'Rúcula', 'Queijo de cabra', 'Nozes', 'Vinagrete balsâmico'], ARRAY['Asse as beterrabas embrulhadas em papel alumínio', 'Descasque e corte em cubos', 'Monte com rúcula', 'Adicione queijo e nozes', 'Regue com vinagrete'], 'Beterraba assada fica mais doce'),
('05b1977b-d73d-4b26-90e3-a87646787207', 'Salada Oriental de Repolho', 'Salada crocante estilo asiático', 'salada-oriental.jpg', 15, 180, 10, 15, 2, ARRAY['2 xícaras de repolho roxo', 'Cenoura ralada', 'Edamame', 'Amendoim', 'Molho de gergelim'], ARRAY['Fatie o repolho bem fino', 'Rale a cenoura', 'Misture com edamame', 'Adicione amendoim', 'Tempere com molho de gergelim'], 'Massageie o repolho para amaciar'),
('05b1977b-d73d-4b26-90e3-a87646787207', 'Salada de Lentilha', 'Salada proteica de lentilhas', 'salada-lentilha.jpg', 30, 290, 18, 35, 2, ARRAY['1 xícara de lentilhas', 'Tomate seco', 'Rúcula', 'Queijo feta', 'Azeite de ervas'], ARRAY['Cozinhe as lentilhas al dente', 'Deixe esfriar', 'Misture com rúcula', 'Adicione tomate seco e feta', 'Tempere com azeite'], 'Não cozinhe demais as lentilhas');

-- Sobremesas fit irresistíveis (3bd3f322-67b8-4258-979c-fe9a17cea503)
INSERT INTO recipes (category_id, title, description, image_url, prep_time, calories, protein, carbs, servings, ingredients, instructions, tips) VALUES
('3bd3f322-67b8-4258-979c-fe9a17cea503', 'Picolé de Frutas', 'Picolé caseiro zero açúcar', 'picole-frutas.jpg', 10, 60, 1, 14, 4, ARRAY['2 xícaras de frutas mistas', '200ml de água de coco', '1 colher de mel ou adoçante'], ARRAY['Bata as frutas com água de coco', 'Adoce a gosto', 'Despeje em formas de picolé', 'Congele por 4 horas'], 'Use frutas bem maduras'),
('3bd3f322-67b8-4258-979c-fe9a17cea503', 'Mousse de Maracujá', 'Mousse leve de maracujá com iogurte', 'mousse-maracuja.jpg', 15, 130, 8, 18, 4, ARRAY['200g de iogurte grego', '100ml de polpa de maracujá', '1 envelope de gelatina', 'Adoçante a gosto'], ARRAY['Hidrate a gelatina', 'Misture iogurte com maracujá', 'Adicione a gelatina dissolvida', 'Leve à geladeira por 3 horas'], 'Decore com sementes de maracujá'),
('3bd3f322-67b8-4258-979c-fe9a17cea503', 'Torta de Limão Fit', 'Torta cremosa de limão sem açúcar', 'torta-limao.jpg', 30, 180, 10, 20, 8, ARRAY['1 xícara de aveia', '3 colheres de óleo de coco', '1 lata de leite condensado zero', 'Suco de 3 limões', 'Raspas de limão'], ARRAY['Triture a aveia e misture com óleo de coco', 'Forre uma forma e asse por 10 min', 'Misture leite condensado com limão', 'Despeje na base assada', 'Leve à geladeira por 4 horas'], 'Decore com raspas de limão'),
('3bd3f322-67b8-4258-979c-fe9a17cea503', 'Docinho de Coco', 'Docinho de coco com leite em pó', 'docinho-coco.jpg', 20, 70, 3, 10, 12, ARRAY['1 xícara de coco ralado', '1/2 xícara de leite em pó', '3 colheres de leite condensado zero', 'Coco para decorar'], ARRAY['Misture todos os ingredientes', 'Amasse até formar uma massa', 'Faça bolinhas', 'Passe no coco ralado'], 'Leve à geladeira para firmar'),
('3bd3f322-67b8-4258-979c-fe9a17cea503', 'Pavê de Chocolate Fit', 'Pavê cremoso com cacau', 'pave-chocolate.jpg', 25, 200, 15, 22, 6, ARRAY['1 pacote de biscoito integral', 'Creme de cacau fit', 'Leite desnatado', 'Whey de chocolate', 'Cacau em pó'], ARRAY['Prepare um creme com whey e leite', 'Adicione cacau', 'Monte camadas com biscoitos', 'Finalize com cacau em pó', 'Leve à geladeira por 4 horas'], 'Deixe os biscoitos amolecerem bem')