-- Café da manhã para aguentar o dia (5 novas receitas)
INSERT INTO recipes (category_id, title, description, image_url, prep_time, ingredients, instructions, tips, calories, protein, carbs, servings) VALUES
('11bff80f-bd8f-4c71-8c91-05256c8f4eaf', 'Suco Verde Detox', 'Suco revigorante com couve, limão e gengibre para começar o dia', 'suco-verde-detox.jpg', 5, ARRAY['2 folhas de couve', '1 maçã verde', 'Suco de 1 limão', '1 pedaço pequeno de gengibre', '200ml de água de coco', 'Gelo a gosto'], ARRAY['Lave bem a couve e a maçã', 'Corte a maçã em pedaços removendo as sementes', 'Descasque o gengibre', 'Bata todos os ingredientes no liquidificador', 'Coe se preferir e sirva com gelo'], 'Tome em jejum para potencializar os benefícios detox. Adicione hortelã para um sabor refrescante.', 85, 2, 18, 1),

('11bff80f-bd8f-4c71-8c91-05256c8f4eaf', 'Ovo Cozido com Abacate', 'Café da manhã proteico e nutritivo com gorduras boas', 'ovo-abacate.jpg', 12, ARRAY['2 ovos', '1/2 abacate maduro', 'Sal e pimenta a gosto', 'Azeite extra virgem', 'Salsinha picada'], ARRAY['Cozinhe os ovos por 10 minutos para gema firme ou 7 para cremosa', 'Resfrie em água gelada e descasque', 'Corte o abacate em fatias', 'Monte no prato com os ovos cortados ao meio', 'Tempere com sal, pimenta, azeite e salsinha'], 'Ótima fonte de proteína e gorduras saudáveis. Ideal para quem faz dieta low carb.', 320, 14, 8, 1),

('11bff80f-bd8f-4c71-8c91-05256c8f4eaf', 'Vitamina de Banana com Aveia', 'Vitamina cremosa e energética para manhãs agitadas', 'vitamina-banana.jpg', 5, ARRAY['1 banana madura', '200ml de leite desnatado', '2 colheres de aveia', '1 colher de mel', 'Canela a gosto'], ARRAY['Corte a banana em rodelas', 'Coloque todos os ingredientes no liquidificador', 'Bata até ficar homogêneo e cremoso', 'Sirva imediatamente'], 'Use banana congelada para uma textura mais cremosa. Adicione whey protein para mais proteína.', 245, 8, 42, 1),

('11bff80f-bd8f-4c71-8c91-05256c8f4eaf', 'Wrap Integral de Ovo', 'Wrap prático recheado com ovos mexidos e vegetais', 'wrap-ovo.jpg', 10, ARRAY['1 wrap integral', '2 ovos', '1/4 tomate picado', 'Espinafre fresco', 'Queijo cottage', 'Sal e pimenta'], ARRAY['Bata os ovos com sal e pimenta', 'Faça os ovos mexidos em fogo baixo', 'Aqueça levemente o wrap', 'Recheie com ovos, tomate, espinafre e cottage', 'Enrole e sirva'], 'Prepare os ingredientes na noite anterior para agilizar o café da manhã.', 285, 18, 22, 1),

('11bff80f-bd8f-4c71-8c91-05256c8f4eaf', 'Panqueca de Abobrinha', 'Panqueca salgada low carb rica em fibras', 'panqueca-abobrinha.jpg', 15, ARRAY['1 abobrinha média ralada', '2 ovos', '2 colheres de farinha de aveia', 'Sal e temperos a gosto', 'Azeite para untar'], ARRAY['Rale a abobrinha e esprema para tirar o excesso de água', 'Misture com ovos, farinha e temperos', 'Aqueça uma frigideira antiaderente untada', 'Despeje porções da massa e espalhe', 'Doure dos dois lados'], 'Sirva com iogurte natural ou cream cheese light. Fica crocante por fora e macia por dentro.', 165, 12, 10, 2);

-- Doces sem fugir da dieta (5 novas receitas)
INSERT INTO recipes (category_id, title, description, image_url, prep_time, ingredients, instructions, tips, calories, protein, carbs, servings) VALUES
('7431747a-5166-4cf9-a9d5-76d1d1cdf5ed', 'Gelatina Proteica de Frutas', 'Sobremesa leve e refrescante rica em proteína', 'gelatina-proteica.jpg', 10, ARRAY['1 envelope de gelatina sem sabor', '1 scoop de whey de morango', '200ml de água quente', '100ml de água fria', 'Frutas vermelhas para decorar'], ARRAY['Dissolva a gelatina na água quente', 'Adicione a água fria e misture bem', 'Acrescente o whey e bata para não formar grumos', 'Despeje em forminhas e leve à geladeira por 4 horas', 'Desenforme e decore com frutas'], 'Use qualquer sabor de whey que preferir. Fica ainda melhor com camadas de sabores diferentes.', 95, 22, 4, 2),

('7431747a-5166-4cf9-a9d5-76d1d1cdf5ed', 'Frozen de Iogurte com Frutas', 'Frozen caseiro cremoso sem açúcar adicionado', 'frozen-iogurte.jpg', 8, ARRAY['200g de iogurte natural congelado', '1 banana congelada', '1/2 xícara de morangos', 'Adoçante a gosto', 'Granola para decorar'], ARRAY['Congele o iogurte em cubos por pelo menos 4 horas', 'Bata no processador com banana e morangos', 'Adoce se necessário', 'Sirva imediatamente decorado com granola'], 'Congele as frutas com antecedência para textura perfeita. Sirva imediatamente após bater.', 145, 8, 24, 2),

('7431747a-5166-4cf9-a9d5-76d1d1cdf5ed', 'Cocada Fit de Forno', 'Cocada crocante assada sem açúcar refinado', 'cocada-fit.jpg', 25, ARRAY['2 xícaras de coco ralado sem açúcar', '1 lata de leite condensado diet', '2 claras de ovo', '1 colher de essência de baunilha'], ARRAY['Pré-aqueça o forno a 180°C', 'Misture o coco com leite condensado e baunilha', 'Bata as claras em neve e incorpore delicadamente', 'Forme bolinhas em assadeira forrada', 'Asse por 15-20 minutos até dourar'], 'Não abra o forno nos primeiros 10 minutos. Guarde em pote fechado por até 5 dias.', 85, 2, 8, 15),

('7431747a-5166-4cf9-a9d5-76d1d1cdf5ed', 'Bombom de Coco Fit', 'Bombom caseiro com recheio cremoso de coco', 'bombom-coco.jpg', 20, ARRAY['100g de coco ralado', '50g de leite em pó desnatado', '2 colheres de óleo de coco', 'Adoçante a gosto', '50g de chocolate 70% derretido'], ARRAY['Misture coco ralado, leite em pó e adoçante', 'Adicione óleo de coco derretido e misture bem', 'Forme bolinhas e leve ao freezer por 15 minutos', 'Derreta o chocolate e banhe os bombons', 'Leve à geladeira para firmar'], 'Use chocolate 70% ou mais para manter low carb. Guarde na geladeira por até 1 semana.', 95, 2, 6, 10),

('7431747a-5166-4cf9-a9d5-76d1d1cdf5ed', 'Banana Caramelizada Fit', 'Banana doce e caramelizada sem açúcar', 'banana-caramelizada.jpg', 8, ARRAY['2 bananas maduras', '1 colher de óleo de coco', 'Canela em pó', 'Adoçante a gosto', 'Iogurte natural para servir'], ARRAY['Corte as bananas em rodelas grossas', 'Aqueça o óleo de coco em frigideira', 'Doure as bananas dos dois lados', 'Polvilhe canela e adoçante', 'Sirva quente com iogurte'], 'Use bananas firmes para não desmancharem. Fica incrível com uma bola de sorvete de banana.', 135, 2, 28, 2);

-- Jantares leves e nutritivos (5 novas receitas)
INSERT INTO recipes (category_id, title, description, image_url, prep_time, ingredients, instructions, tips, calories, protein, carbs, servings) VALUES
('18d7a8d4-e335-4731-9f8e-db4d32140013', 'Sopa Detox de Legumes', 'Sopa leve e nutritiva para limpar o organismo', 'sopa-detox.jpg', 30, ARRAY['2 cenouras', '1 abobrinha', '1 chuchu', '1 cebola', '2 dentes de alho', '1 litro de água', 'Sal e ervas a gosto'], ARRAY['Pique todos os legumes em cubos', 'Refogue cebola e alho no azeite', 'Adicione os legumes e a água', 'Cozinhe por 20 minutos até ficarem macios', 'Bata no liquidificador se preferir cremosa'], 'Varie os legumes conforme preferência. Adicione gengibre para potencializar o efeito detox.', 95, 3, 18, 3),

('18d7a8d4-e335-4731-9f8e-db4d32140013', 'Canja Leve de Frango', 'Canja reconfortante com poucas calorias', 'canja-leve.jpg', 35, ARRAY['200g de peito de frango', '1/2 xícara de arroz integral', '1 cenoura picada', '1 cebola', '2 dentes de alho', '1 litro de água', 'Salsinha e sal'], ARRAY['Cozinhe o frango na água com cebola e alho', 'Retire o frango e desfie', 'Na mesma água, cozinhe o arroz e cenoura', 'Devolva o frango desfiado', 'Finalize com salsinha'], 'Use peito de frango para versão mais leve. O caldo pode ser feito com antecedência e congelado.', 185, 22, 16, 3),

('18d7a8d4-e335-4731-9f8e-db4d32140013', 'Omelete de Forno com Legumes', 'Omelete grande assado perfeito para o jantar', 'omelete-forno-jantar.jpg', 25, ARRAY['4 ovos', '1 abobrinha pequena', '1 tomate', '1/2 cebola', 'Queijo cottage', 'Sal e orégano'], ARRAY['Pré-aqueça o forno a 180°C', 'Bata os ovos com sal e orégano', 'Pique os legumes em cubos pequenos', 'Misture tudo e despeje em forma untada', 'Asse por 20 minutos até dourar'], 'Adicione outros legumes que tiver na geladeira. Fica ótimo frio no lanche do dia seguinte.', 195, 16, 8, 2),

('18d7a8d4-e335-4731-9f8e-db4d32140013', 'Berinjela Recheada Light', 'Berinjela assada recheada com carne magra', 'berinjela-recheada.jpg', 40, ARRAY['2 berinjelas', '200g de carne moída magra', '1 tomate picado', '1 cebola', 'Queijo minas ralado', 'Temperos a gosto'], ARRAY['Corte as berinjelas ao meio e retire parte da polpa', 'Refogue a carne com cebola e tomate', 'Adicione a polpa da berinjela picada', 'Recheie as metades e cubra com queijo', 'Asse a 200°C por 25 minutos'], 'Deixe as berinjelas de molho em água com sal para tirar o amargor antes de usar.', 245, 24, 12, 2),

('18d7a8d4-e335-4731-9f8e-db4d32140013', 'Salada de Jantar Completa', 'Salada nutritiva com proteína para jantar leve', 'salada-jantar.jpg', 15, ARRAY['Mix de folhas verdes', '100g de frango grelhado desfiado', '1/2 pepino', '1 tomate', 'Grão-de-bico cozido', 'Azeite e limão'], ARRAY['Lave e seque bem as folhas', 'Corte pepino e tomate em cubos', 'Monte a salada com todos os ingredientes', 'Adicione o frango desfiado e grão-de-bico', 'Tempere com azeite e limão na hora de servir'], 'Prepare os ingredientes com antecedência e monte na hora. Varie a proteína com atum ou ovo cozido.', 285, 28, 18, 1);

-- Lanches rápidos e saudáveis (5 novas receitas)
INSERT INTO recipes (category_id, title, description, image_url, prep_time, ingredients, instructions, tips, calories, protein, carbs, servings) VALUES
('d639ae08-35ce-409d-a0f4-27e6db85dc2b', 'Crepioca de Queijo e Tomate', 'Crepioca crocante com recheio leve', 'crepioca-queijo.jpg', 10, ARRAY['2 colheres de tapioca', '1 ovo', 'Queijo branco em cubos', 'Tomate em rodelas', 'Orégano'], ARRAY['Misture a tapioca com o ovo', 'Despeje em frigideira antiaderente quente', 'Quando firmar, adicione queijo e tomate', 'Dobre ao meio e deixe dourar', 'Finalize com orégano'], 'A massa deve ficar bem fina para ficar crocante. Sirva imediatamente.', 195, 12, 18, 1),

('d639ae08-35ce-409d-a0f4-27e6db85dc2b', 'Patê de Atum Light', 'Patê proteico para acompanhar torradas', 'pate-atum.jpg', 5, ARRAY['1 lata de atum light escorrido', '2 colheres de iogurte natural', '1 colher de mostarda', 'Cebolinha picada', 'Sal e pimenta'], ARRAY['Escorra bem o atum', 'Amasse com um garfo', 'Misture com iogurte e mostarda', 'Adicione cebolinha e tempere', 'Sirva com torradas integrais'], 'Fica ainda melhor se deixar na geladeira por 30 minutos antes de servir.', 145, 22, 3, 2),

('d639ae08-35ce-409d-a0f4-27e6db85dc2b', 'Chips de Abobrinha', 'Chips crocantes e saudáveis de abobrinha', 'chips-abobrinha.jpg', 20, ARRAY['2 abobrinhas médias', 'Azeite em spray', 'Sal e páprica', 'Alho em pó', 'Orégano'], ARRAY['Corte as abobrinhas em rodelas finas', 'Disponha em assadeira forrada', 'Borrife azeite e tempere', 'Asse a 200°C por 15-20 minutos', 'Vire na metade do tempo'], 'Corte bem fino para ficarem crocantes. Não empilhe as rodelas na assadeira.', 65, 3, 8, 2),

('d639ae08-35ce-409d-a0f4-27e6db85dc2b', 'Rolinho de Peito de Peru', 'Rolinho rápido proteico para lanches', 'rolinho-peru.jpg', 5, ARRAY['4 fatias de peito de peru', 'Cream cheese light', 'Rúcula', 'Tomate seco', 'Pimenta do reino'], ARRAY['Espalhe cream cheese nas fatias de peru', 'Adicione rúcula e pedaços de tomate seco', 'Enrole firmemente', 'Corte ao meio se preferir', 'Sirva frio'], 'Prepare vários e leve como lanche para o trabalho. Guarde na geladeira por até 2 dias.', 95, 12, 3, 2),

('d639ae08-35ce-409d-a0f4-27e6db85dc2b', 'Mix de Oleaginosas', 'Mix energético de castanhas e sementes', 'mix-oleaginosas.jpg', 2, ARRAY['Castanha de caju', 'Castanha do Pará', 'Amêndoas', 'Nozes', 'Sementes de abóbora'], ARRAY['Separe uma porção de cada oleaginosa', 'Misture em um pote', 'Consuma uma porção de 30g por dia'], 'Não ultrapasse 30g por porção devido ao alto valor calórico. Guarde em pote fechado.', 185, 5, 6, 1);